const actionTypes = {
    GET_HOME: 'GET_HOME',
    SET_CUR_SONG_ID: 'SET_CUR_SONG_ID',
    SET_CUR_SONG_DATA: 'SET_CUR_SONG_DATA',
    SET_CUR_ALBUM_ID: 'SET_CUR_ALBUM_ID',
    LOADING: 'LOADING',
    SET_RECENT_SONGS: 'SET_RECENT_SONGS',
    SET_RECENT_SEARCH: 'SET_RECENT_SEARCH',

    //music
    PLAY: "PLAY",
    SET_ALBUM: 'SET_ALBUM',
    PLAYLIST: 'PLAYLIST',
    SEARCH: 'SEARCH',

    //artist
    SET_CUR_ARTIST_DATA: 'SET_CUR_ARTIST_DATA'
}

export default actionTypes